config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'web/books#index'

  scope module: 'web' do
    resources :books  do
      resources :comments
    end
  end
end

app/models/admin.rb
# frozen_string_literal: true

##
# Администратор системы
class Admin < User
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :author, presence: true

  broadcasts_to ->(_book) { 'books' }, insert_by: :prepend
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :book

  validates :text, presence: true
end

app/models/user.rb
# frozen_string_literal: true

##
# Пользователи системы
class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  def name
    email.split('@').first.capitalize
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/web/books_controller.rb
# frozen_string_literal: true

module Web
  ##
  # Управление книгами
  class BooksController < ApplicationController
    before_action :authenticate_user!, except: %i[index show]
    before_action :set_book, only: %i[show edit update destroy]

    def index
      @books = Book.all
    end

    def new
      @book = Book.new
    end

    def create
      @book = Book.new(book_params)

      if @book.save
        respond_to do |format|
          format.html { redirect_to books_path, notice: t('success_create') }
          format.turbo_stream { flash.now[:notice] = t('success_create') }
        end
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @book.update(book_params)
        redirect_to book_path(@book), notice: t('success_update')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @book.destroy

      respond_to do |format|
        format.html { redirect_to quotes_path, notice: t('success_destroy') }
        format.turbo_stream { flash.now[:notice] = t('success_destroy') }
      end
    end

    private

    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:author, :title, :description)
    end
  end
end

app/controllers/web/comments_controller.rb
# frozen_string_literal: true

module Web
  class CommentsController < ApplicationController
    def create
      @book = Book.find(params[:book_id])
      @comment = @book.comments.create(comment_params)
      redirect_to book_path(@book)
    end

    private

    def comment_params
      params.require(:comment).permit(:text)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend 'flash', partial: 'layouts/flash'
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flash__message" data-controller="removals" data-action="animationend->removals#remove">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <% if user_signed_in? %>
    <div class="navbar__name">
      <%= current_user.name %>
    </div>
    <%= button_to t("web.sign_out"),
                  destroy_user_session_path,
                  method: :delete,
                  class: "btn btn--dark" %>
  <% else %>
    <%= link_to t("web.sign_in"),
                new_user_session_path,
                class: "btn btn--dark navbar__right" %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCatalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="flash">
      <%= render "layouts/flash" %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/web/books/_book.html.erb
<%= turbo_frame_tag book do %>
  <div class="book ">
    <%= link_to book.title, book_path(book), class: "book__link",
                data: { turbo_frame: "_top" } %>
  </div>
<% end %>

app/views/web/books/_comment.html.erb
<% if comment.text.present? %>
  <div class="book">
    <%= comment.text %>
  </div>
<% end %>

app/views/web/books/_comment_form.html.erb
<h2><%= t("book.comment") %></h2>
<%= form_with model: [ book, book.comments.build ], class: "form" do |form| %>
  <div class="form__group">
    <%= form.text_area :text, class: "form__input" %>
  </div>
  <div class="">
    <%= form.submit t("web.submit"), class: "btn btn--secondary" %>
  </div>
<% end %>

app/views/web/books/_comment_list.html.erb
<h2><%= t("book.comments") %></h2>
<% if book.comments.size > 1 %>
  <% book.comments.each do |comment| %>
    <%= render "comment", comment: comment %>
  <% end %>
<% else %>
  <p><%= t("book.comment_list_blank") %></p>
<% end %>

app/views/web/books/_form.html.erb
<%= form_with model: book, html: { class: "form" } do |f| %>
  <% if book.errors.any? %>
    <div class="error-message">
      <%= book.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <div class="form__group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form__input" %>

    <%= f.label :author %>
    <%= f.text_field :author, class: "form__input" %>

    <%= f.label :description %>
    <%= f.text_area :description, class: "form__input" %>

    <div class="book__actions form__footer">
      <% if book.new_record? %>
        <%= link_to t("web.cancel"), books_path, class: "btn btn--light" %>
      <% else %>
        <%= link_to t("web.cancel"), book_path(book), class: "btn btn--light",
                    data: { turbo_frame: "_top" } %>
      <% end %>
      <%= f.submit t("web.submit"), class: "btn btn--secondary" %>
    </div>
  </div>
<% end %>

app/views/web/books/create.turbo_stream.erb
<%= turbo_stream.prepend "books", @book %>
<%= turbo_stream.update Book.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/web/books/destroy.turbo_stream.erb
<%= turbo_stream.remove @book %>
<%= render_turbo_stream_flash_messages %>

app/views/web/books/edit.html.erb
<div class="book">
  <div class="header">
    <h2><%= t("web.edit") %></h2>
  </div>
  <%= render "form", book: @book %>
</div>

app/views/web/books/index.html.erb
<%= turbo_stream_from "books" %>
<div class="header">
  <h1><%= t("book.list") %></h1>
  <% if current_user %>
    <%= link_to t("book.new"), new_book_path, class: "btn btn--primary", 
                data: { turbo_frame: dom_id(Book.new) } %>
  <% end %>
</div>
<%= turbo_frame_tag Book.new %>
<%= turbo_frame_tag "books" do %>
  <%= render @books %>
<% end %>

app/views/web/books/new.html.erb
<%= turbo_frame_tag @book do %>
  <div class="book">
    <div class="header">
      <h2><%= t("web.create") %></h2>
    </div>
    <%= render "form", book: @book %>
  </div>
<% end %>

app/views/web/books/show.html.erb
<%= link_to t("web.back_to"), books_path %>
<div class="header">
  <h1><%= @book.title %></h1>
  <% if current_user %>
    <div class="book__actions">
      <%= link_to t("web.destroy"), book_path(@book), class: "btn btn--light",
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      <%= link_to t("web.edit"), edit_book_path(@book), class: "btn btn--secondary" %>
    </div>
  <% end %>
</div>
<div class="book">
  <div>
    <strong><%= t("book.author") %></strong>
    <%= @book.author %>
  </div>
  <% if @book.description.present? %>
    <div>
      <strong><%= t("book.description") %></strong>
      <%= @book.description %>
    </div>
  <% end %>
</div>

<%= render "comment_form", book: @book %>
<%= render "comment_list", book: @book %>